In [53]:
import pandas as pd
import random

In [54]:
df = pd.read_csv("docs/trial_detail.csv")

In [56]:
by_candidate = df.groupby("candidate_id")["trial_phase"].agg(lambda s: {str(v).strip() for v in s.dropna()})

has_phase1 = by_candidate.apply(lambda phases: "Phase 1" in phases)
has_other_phase = by_candidate.apply(lambda phases: any(p != "Phase 1" for p in phases))

matched = has_phase1 & has_other_phase

numerator = int(matched.sum())
denominator = int(len(by_candidate))
pct = (numerator / denominator * 100) if denominator else 0.0

print(f"{numerator}/{denominator} candidate_id groups = {pct:.2f}%")

8441/177141 candidate_id groups = 4.77%

In [60]:
df.iloc[4]

candidate_id                                          db:DB00162__retinitis pigmentosa
candidate_drug                                                               vitamin a
candidate_drug_raw                                                           Vitamin A
candidate_indication                                              retinitis pigmentosa
candidate_modality                                                      small_molecule
candidate_disease_area                                                   ophthalmology
candidate_outcome                                                              Unknown
candidate_highest_phase                                                        Phase 3
candidate_drugbank_id                                                          DB00162
candidate_mesh_drug                                                          vitamin a
candidate_mesh_indication                                         retinitis pigmentosa
nct_id                                                                     NCT00065455
trial_intervention                                                           Vitamin A
trial_indication                                                  Retinitis Pigmentosa
trial_phase                                                                    Phase 1
trial_status                                                                 Completed
trial_mesh_intervention_terms                                                Vitamin A
trial_mesh_condition_terms                                        Retinitis Pigmentosa
trial_mesh_condition_tree_numbers      C11.270.684|C11.768.585.658.500|C16.320.290.684
trial_start_date                                                            2003-07-17
trial_completion_date                                                       2009-05-06
trial_is_single_arm                                                               True
trial_sponsor                                             National Eye Institute (NEI)
trial_title                          Investigating the Effect of Vitamin A Suppleme...
Name: 4, dtype: object

In [83]:
drug = "erythropoetin"
indication = "sclerosis"
df[df.candidate_drug.str.contains(drug) & df.candidate_indication.str.contains(indication)][["candidate_id", "candidate_drug", "candidate_indication"]]

Empty DataFrame
Columns: [candidate_id, candidate_drug, candidate_indication]
Index: []

In [80]:
for n, g in df.groupby("candidate_id"):
    if random.random() < 0.001:
        break
g

,candidate_id,candidate_drug,candidate_drug_raw,candidate_indication,candidate_modality,candidate_disease_area,candidate_outcome,candidate_highest_phase,candidate_drugbank_id,candidate_mesh_drug,...,trial_phase,trial_status,trial_mesh_intervention_terms,trial_mesh_condition_terms,trial_mesh_condition_tree_numbers,trial_start_date,trial_completion_date,trial_is_single_arm,trial_sponsor,trial_title
175965,db:DB00016__amyotrophic lateral sclerosis,erythropoetin (epo),erythropoetin (EPO),chronic stroke,unknown,neurology,Unknown,Phase 2,DB00016,erythropoietin,...,Phase 2,Completed,Erythropoietin|Granulocyte Colony-Stimulating ...,Amyotrophic Lateral Sclerosis,C10.228.854.139|C10.574.562.250|C10.574.950.05...,2006-03-31,2009-03-31,False,University Hospital Muenster,Influence of G-CSF and EPO on Associative Lear...
175966,db:DB00016__amyotrophic lateral sclerosis,erythropoetin (epo),erythropoetin (EPO),chronic stroke,unknown,neurology,Unknown,Phase 2,DB00016,erythropoietin,...,Phase 2,Completed,Erythropoietin|Granulocyte Colony-Stimulating ...,Amyotrophic Lateral Sclerosis,C10.228.854.139|C10.574.562.250|C10.574.950.05...,2006-03-31,2009-03-31,False,University Hospital Muenster,Influence of G-CSF and EPO on Associative Lear...

In [18]:
by_candidate.iloc[:30]

candidate_id
db:DB00001__cardiovascular diseases                                                                                {Phase 2}
db:DB00002__adenocarcinoma                                                                                {Phase 1, Phase 2}
db:DB00002__adenocarcinoma of esophagus                                                                            {Phase 2}
db:DB00002__advanced colorectal cancer                                                                             {Phase 2}
db:DB00002__advanced non-small cell lung cancer                                                                    {Phase 2}
db:DB00002__astrocytoma                                                                                            {Unknown}
db:DB00002__blood protein disorders                                                                                {Phase 2}
db:DB00002__breast diseases                                                                               {Phase 1, Unknown}
db:DB00002__bronchial neoplasms                                                         {Phase 1, Phase 3, Unknown, Phase 2}
db:DB00002__carcinoma                                                                            {Phase 1, Phase 3, Phase 2}
db:DB00002__colonic diseases                                                   {Unknown, Phase 4, Phase 2, Phase 1, Phase 3}
db:DB00002__colorectal neoplasms                                                                                   {Phase 2}
db:DB00002__digestive system diseases                                                                              {Phase 2}
db:DB00002__endometrial neoplasms                                                                                  {Phase 2}
db:DB00002__female urogenital diseases                                                                             {Phase 2}
db:DB00002__head and neck neoplasms                                                              {Phase 1, Phase 3, Phase 2}
db:DB00002__lung diseases                                                                                          {Phase 2}
db:DB00002__malignant solid tumour                                                                                 {Phase 1}
db:DB00002__mucinous gastrointestinal adenocarcinoma                                                               {Phase 2}
db:DB00002__neoplasms                                                                                     {Phase 1, Phase 2}
db:DB00003__congenital, hereditary, and neonatal diseases and abnormalities                               {Phase 3, Phase 2}
db:DB00003__ear diseases                                                                                           {Phase 4}
db:DB00003__long term ventilation                                                                                  {Unknown}
db:DB00004__chronic disease                                                                               {Phase 1, Phase 2}
db:DB00004__graft vs host disease                                                                                  {Phase 2}
db:DB00004__hemic and lymphatic diseases                                                                  {Phase 4, Phase 2}
db:DB00004__melanoma                                                                                               {Phase 2}
db:DB00005__acute lung injury                                                                                      {Phase 2}
db:DB00005__adenocarcinoma                                                                                         {Unknown}
db:DB00005__ankylosis                                                                                     {Phase 3, Phase 4}
Name: trial_phase, dtype: object

In [52]:
len(df)

71963

In [51]:
# Sample random group with at least one phase 1 trial
sampled = by_candidate.sample(50, random_state=4)
print(sampled)

candidate_id
name:velcade tm for__genital diseases                                                                          {Unknown}
db:DB11702__small intestine cancer                                                                             {Phase 2}
db:DB00864__dna virus infections                                                                               {Phase 4}
name:adh 1__adnexal diseases                                                                                   {Unknown}
name:orlistat vs metformin__adnexal diseases                                                                          {}
db:DB00560__bile duct diseases                                                                                 {Phase 1}
db:DB00421__diabetes mellitus                                                                                  {Phase 4}
db:DB00480__blood coagulation disorders                                                                        {Phase 2}
db:DB00860__colitis                                                                                            {Phase 3}
name:interleukin__blood protein disorders                                                                      {Phase 1}
db:DB00515__disease attributes                                                                        {Phase 3, Phase 2}
name:beclomethasone dipropionate duration of treatment 56 weeks__asthma                                        {Phase 4}
db:DB00863__acquired immunodeficiency syndrome                                                                 {Phase 1}
db:DB00541__hematologic diseases                                           {Unknown, Phase 4, Phase 2, Phase 1, Phase 3}
db:DB00627__glucose metabolism disorders                                                                       {Phase 4}
db:DB01118__persistant atrial fibrillation                                                                            {}
db:DB00929__neoplasm metastasis                                                                                {Phase 4}
name:mac 321__bronchial neoplasms                                                                              {Phase 2}
db:DB00997__agranulocytosis                                                                                    {Phase 2}
db:DB00631__blood protein disorders                                                                            {Phase 2}
db:DB00130__anemia                                                                                             {Phase 2}
db:DB01033__hematologic diseases                                                    {Phase 3, Unknown, Phase 4, Phase 2}
db:DB00441__biliary tract diseases                                                                             {Phase 2}
name:kallunk oxide__blood-borne infections                                                                     {Unknown}
db:DB01229__stage i bladder cancer ajcc v6 and v7                                                              {Unknown}
name:abt 378 r__blood-borne infections                                                                         {Phase 2}
db:DB05786__female urogenital diseases                                                                         {Phase 2}
db:DB01234__bronchopulmonary dysplasia                                                                         {Phase 3}
db:DB00997__autoimmune diseases                                                                                {Phase 2}
db:DB09155__pulmonary diffusing capacity                                                                       {Phase 1}
db:DB06190__female urogenital diseases                                                                         {Phase 2}
name:vitamins e c__behavior                                                                                    {Unknown}
mesh:observation__melanoma                                                                                     {Phase 3}
db:DB01196__adenocarcinoma                                                                                     {Phase 2}
db:DB00671__unspecified adult solid tumor, protocol specific                                                   {Phase 1}
db:DB00563__hemic and lymphatic diseases                                            {Phase 1, Phase 3, Unknown, Phase 2}
name:r xk469__anemia                                                                                           {Phase 1}
name:abx egf__bronchial neoplasms                                                                              {Phase 2}
db:DB00268__basal ganglia diseases                                                                    {Phase 3, Phase 4}
db:DB00531__glioma                                                                                    {Phase 3, Phase 2}
db:DB00544__hemic and lymphatic diseases                                                              {Phase 1, Phase 2}
db:DB06406__cardiovascular diseases                                                                            {Phase 3}
db:DB00030__brain diseases                                                                                     {Phase 2}
name:mk0518 combination__acquired immunodeficiency syndrome                                                    {Phase 2}
db:DB00300__hiv                                                                                                {Phase 2}
db:DB00605__desmoid tumors                                                                                     {Phase 2}
name:prednisone corticosteroid 1mg kg d for 1 week__ear diseases                                               {Unknown}
name:mk 0518__blood-borne infections                                                                           {Phase 3}
db:DB04900__acquired immunodeficiency syndrome                                                                 {Phase 1}
db:DB00928__previously treated myelodysplastic syndromes                                                       {Unknown}
Name: trial_phase, dtype: object